// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmBSX4BhtvsbWHfEiYB8dVqJA0-qgSDOo',
    appId: '1:760469697120:web:81fd73a5742b79f834c905',
    messagingSenderId: '760469697120',
    projectId: 'loginpage-a4983',
    authDomain: 'loginpage-a4983.firebaseapp.com',
    storageBucket: 'loginpage-a4983.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwpNDt0eMGeZE155fuZ4b1ZOK4M29jjY8',
    appId: '1:760469697120:android:bbb14ab3cd4990b634c905',
    messagingSenderId: '760469697120',
    projectId: 'loginpage-a4983',
    storageBucket: 'loginpage-a4983.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwp2rbdNe9eHcj1SaS7DYjDV_YgpkXz64',
    appId: '1:760469697120:ios:95dbe4380b55d67b34c905',
    messagingSenderId: '760469697120',
    projectId: 'loginpage-a4983',
    storageBucket: 'loginpage-a4983.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwp2rbdNe9eHcj1SaS7DYjDV_YgpkXz64',
    appId: '1:760469697120:ios:95dbe4380b55d67b34c905',
    messagingSenderId: '760469697120',
    projectId: 'loginpage-a4983',
    storageBucket: 'loginpage-a4983.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmBSX4BhtvsbWHfEiYB8dVqJA0-qgSDOo',
    appId: '1:760469697120:web:255b77497769408634c905',
    messagingSenderId: '760469697120',
    projectId: 'loginpage-a4983',
    authDomain: 'loginpage-a4983.firebaseapp.com',
    storageBucket: 'loginpage-a4983.firebasestorage.app',
  );
}
